version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - DOMAIN_NAME
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/:/etc/letsencrypt:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: |
          certonly --reinstall --webroot --webroot-path=/var/www/certbot
          --email ${EMAIL} --agree-tos --no-eff-email
          -d ${DOMAIN_NAME}
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
