name: Deploy to staging

on: [push]

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy deploy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "deploy/vps/*"
        target: ~/vps/
        strip_components: 2

    - name: Running nginx server
      uses: appleboy/ssh-action@v0.1.10
      env:
        DOMAIN_NAME: ${{ env.DOMAIN_NAME }}
        EMAIL: ${{ env.EMAIL }}
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker compose -f vps/docker-compose.yaml up -d
