name: Deploy to staging

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: | 
          echo "Hello World!"
