name: Deploy to staging

on: [push]

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy deploy files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "deploy/vps/*"
        target: ~/vps/
        strip_components: 2

    - name: Running nginx server
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
        EMAIL: ${{ vars.EMAIL }}
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: DOMAIN_NAME,EMAIL
        script: |
          for filename in `find vps -name "*.conf" -type f`; do
            envsubst "$DOMAIN_NAME" < $filename > $filename
          done
          docker compose -f vps/docker-compose-initiate.yaml up -d
